### PR TITLE
🐛 Fix open, edit and reopen handlers

### LINKED ISSUE #19: 🐛 Open, edit and reopen not performing the checks
# Description
`open`, `edit` and `reopen` actions are not performing the checks properly and the result is always a success.

# Details
I will link the debug output for the steps that have happened to #14 as an example:
1. Create a PR with wrong PR Title: success, no Check Run created [log](https://github.com/kubernetes-sigs/kubebuilder-release-tools/pull/14/checks?check_run_id=1417046977#step:3:88)
1. Edit the name to a correct one: success but no Check Run created [log](https://github.com/kubernetes-sigs/kubebuilder-release-tools/pull/14/checks?check_run_id=1417049115#step:3:88)
1. Edit the name to a incorrect one: success, no Check Run created [log](https://github.com/kubernetes-sigs/kubebuilder-release-tools/pull/14/checks?check_run_id=1417146647#step:3:88)
1. Edit the name to a correct one: success but no Check Run created [log](https://github.com/kubernetes-sigs/kubebuilder-release-tools/pull/14/checks?check_run_id=1417703172#step:3:88)
1. Close and reopen the PR: success but no Check Run created [log](https://github.com/kubernetes-sigs/kubebuilder-release-tools/pull/14/checks?check_run_id=1417718916#step:3:88)
1. Ammend commit to force a resynchronize: success, Check Run created in the wrong commit (tracked in #17) [log](https://github.com/kubernetes-sigs/kubebuilder-release-tools/pull/14/checks?check_run_id=1417886057#step:3:88)

As it can be seen in the first 5 steps (corresponding to `open`, `edit`, and `reopen` actions), none of them is providing any debug info and just seccessfully finishing the workflow without checking not creating the Check Runs. Step 6 does check and create the checks (with a bug tracked in #17 and solved in #18).

### PR DESCRIPTION
**Pull request by Adirio**
Some typos were preventing the proper handlers to be called.

Fixes #19

### CODE REVIEW

**Comment by Adirio** [comment]
Requires #23 to get merged first

/hold

**Comment by Adirio** [comment]
#23 merged

/unhold

**Review by DirectXMan12 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
