### PR TITLE
🌱 Organize verify directory

### PR DESCRIPTION
**Pull request by Adirio**
# Description
Move the action framework from `./verify` to `./verify/pkg/action` in order to free `./verify` for the main package which was previously kept in `./verify/cmd`. The framework API has been cleaned up a bit, providing `Action` and `Plugin` interfaces and corresponding constructor methods.

Additionally, the checks for PR body descriptiveness and Issue tags on PR titles which were previously grouped under a single plugin have been split into two different plugins.

### CODE REVIEW

**Review by DirectXMan12 — COMMENTED** [review]
/lgtm
/approve

**Comment by Adirio** [comment]
@DirectXMan12 Could you please reapply `lgtm` as it needed to be rebased?

**Pull request merged**
