### PR TITLE
🐛 Duplicate the check run even if we need to re-run the tests

### LINKED ISSUE #17: 🐛 Updating a Check Run HeadSHA is not working
# Description
When a (force-)push is issued, the PR Verifier action tries to update the related check runs to the new commit. `github.UpdateCheckRunOptions` does provide a `HeadSHA` field but it is not updating the `HeadSHA` (potential GitHub actions bug). Therefore, we need to create a new CheckRun for the new commit instead of trying to rebind it.

Related: https://github.com/google/go-github/issues/1652

### PR DESCRIPTION
**Pull request by Adirio**
#17 wasn't fully solved by #18, see https://github.com/kubernetes-sigs/kubebuilder-release-tools/issues/17#issuecomment-730275334

Fixes #17

### CODE REVIEW

**Comment by Adirio** [comment]
Requires #21 to get merged first

/hold

**Comment by DirectXMan12** [comment]
generally looks fine (although if we choose to re-target on synchronize we might just want to immediately move to sending the results to HEAD, instead of duplicating them at the end), but see my comment on #21 for why we should not include #21

**Comment by Adirio** [comment]
> generally looks fine (although if we choose to re-target on synchronize we might just want to immediately move to sending the results to HEAD, instead of duplicating them at the end)

In most cases, that check will already be done and we will just send the results to HEAD. It computes them back if it can't find the Check Run and thus has to create it. I chose to send them back to the `before` commit too in order to avoid a hanging unfinished check.

**Comment by Adirio** [comment]
The dependency on #21 has been replaced by a dependency on #23, which just provides the improved debug output.

**Comment by Adirio** [comment]
#23 merged

/unhold

**Review by DirectXMan12 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
