### PR TITLE
:sparkles: Release Notes Tooling & PR Verifier

### PR DESCRIPTION
**Pull request by DirectXMan12**
This adds a release notes composer based off of CR's hack/release scripts & the subsequent cluster-api Go release notes tooling by vincepri, whence it borrow heavily.

It lives in `notes/`, and includes both common utilities for reuse in various packages, as well as a common tool at the base that tries to figure out the situation mostly on its own.

This also adds a framework for running basic PR checks in Go, running them in GitHub actions, and writing the results.  We make use of this framework to add a GitHub action at the root of this repository that verifies the PR title for release notes and checks that the PR description meets some basic descriptiveness standards.

The actions-related code lives in `verify/`, with the action's main in `verify/cmd` (see the Dockerfile at the root).

### CODE REVIEW

**Comment by DirectXMan12** [comment]
NB: once this is merged, it'll start running against this repo -- for security reasons, the action runs against the HEAD of the base branch, not the PR.

/assign @vincepri 

for review

**Comment by DirectXMan12** [comment]
(yes, I made this way more complicated, but it also does a bit more stuff automatically, like figuring out how to look back releases, sync upstreams, etc).

**Comment by vincepri** [comment]
This looks great, I took a quick glance and ready to merge it, going to do a small pass later today and LGTM it unless there is anything that stands out

**Comment by vincepri** [comment]
/lgtm

!! thank you for doing this 🎉 

I'll make sure to open some issues / PRs to use these tools in CAPI

**Pull request merged**
